#!/usr/bin/env python

from pyar_de.de import run_de

def main():
    import argparse
    program_description = """A program to do global optimization with
    Differential Evolution algorithm using SciPy.optimize.differential_evolution
    Currently interfaced with ORCA and Gaussian packages.
    """
    example = """
    Example:
        python pyar-de.py C H H H H --software orca -c 0 -m 1 --keywords '! hf-3c'

        python pyar-de.py C H H H H --software gaussian -c 0 -m 1 --keywords '# b3lyp def2SVP'

    """
    parser = argparse.ArgumentParser(prog='pyar-de',
                                     description=program_description,
                                     epilog=example,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)

    parser.add_argument("atoms", metavar='Z',
                        type=str, nargs='+',
                        help='Atomic atoms of the atomic cluster. '
                             'For example, for a C4 cluster, provide C C C C. '
                             'For CH4, C H H H H')
    parser.add_argument("--software", type=str,
                        choices=['gaussian', 'orca'],
                        required=True, help="Software")
    # noinspection SpellCheckingInspection
    parser.add_argument('-nprocs', '--nprocs', metavar='n',
                        type=int, help='The number of processors/cores to be '
                                       'used by the quantum chemistry software.'
                        )
    parser.add_argument("-c", "--charge", type=int, required=True,
                        metavar='c',
                        help="Total charge of the system")
    parser.add_argument("-m", "--multiplicity", type=int,
                        required=True,
                        metavar='m',
                        help="Multiplicity of the system")
    parser.add_argument('--keywords', type=str, required=True,
                        help='Keyword line for the QM software input. '
                             'E.g., For gaussian input, "# PBE def2SVP"'
                             'Fro ORCA input, "! RI PBE def2-SVP D3BJ"')

    parser.add_argument('--extra-keywords', type=str,
                        help='Keyword line for the QM software input. '
                             'E.g., For gaussian input, "%%mem=2Gnk"'
                             'Fro ORCA input, and "%%scf maxiter=100 end"')

    parser.add_argument('--n-iterations', metavar='n', default=30,
                        type=int, help='The number of iterations. Default=30'
                        )
    args = parser.parse_args()
    energy, coordinate = run_de(vars(args))

main()